(******************************************************************************)
(*                                                                            *)
(*                          CODE OF CANON LAW (1983)                          *)
(*                                                                            *)
(*     Formalizing the 1983 Code of Canon Law: marriage validity,             *)
(*     ordination requirements, excommunication latae sententiae,             *)
(*     tribunal procedures, and sacramental disciplines.                      *)
(*                                                                            *)
(*     "Salus animarum suprema lex."                                          *)
(*     - Canon 1752                                                           *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
